name: "Custom Base Image Build and Use"
description: "Build a custom Docker image and use it in the next pipeline step"
iconUrl: "https://buildkite.com/icon-32x32.png"

configuration:
  properties:
    repository:
      type: string
      displayName: "Repository"
      description: "The repository containing the Dockerfile and pipeline configuration"
    default_queue:
      type: string
      displayName: "Default Queue"
      description: "Queue name for building the image (uses default base image)"
      default: "linux-arm64-small-default"
    custom_queue:
      type: string
      displayName: "Custom Queue" 
      description: "Queue name that will use the custom built image"
      default: "linux-arm64-small-custom"
    image_name:
      type: string
      displayName: "Image Name"
      description: "Name for the Docker image (will be tagged as latest)"
      default: "base"

  steps:
    - label: ":rocket: Create pipeline from template"
      command: |
        echo "Creating Buildkite pipeline from template..."
        echo ""
        echo "This will create a pipeline that:"
        echo "1. Builds a custom Docker image on '${default_queue}' queue"
        echo "2. Uses the custom image on '${custom_queue}' queue" 
        echo ""
        echo "Make sure both queues exist in your Buildkite organization!"
        echo ""
        echo "After the first successful build:"
        echo "- Copy the registry URL from the build annotation"
        echo "- Configure '${custom_queue}' queue to use that image URL"

pipeline:
  repository: "${repository}"
  pipeline: ".buildkite/pipeline.yml"
  branch_configuration: "main /*"
  skip_intermediate_builds: true
  
  env:
    DEFAULT_QUEUE: "${default_queue}"
    CUSTOM_QUEUE: "${custom_queue}"
    IMAGE_NAME: "${image_name}"
