steps:
  - key: base_image
    label: ":docker: Create base image"
    agents:
      queue: linux-arm64-small-default # a dedicated queue using the default base image
    command: |
      export REGISTRY="$(nsc workspace describe -o json -k registry_url)"
      export SERVICE="base" # name of the image
      export DOCKER_REPOSITORY="$${REGISTRY}/$${SERVICE}:latest"

      docker buildx build \
        --no-cache \
        --file .buildkite/Dockerfile.build \
        --platform linux/amd64,linux/arm64 \
        --tag "$${DOCKER_REPOSITORY}" \
        --progress plain \
        --push .

      buildkite-agent annotate --style "success" ":rocket: Image pushed to $${DOCKER_REPOSITORY} :rocket:"

  - key: custom_image
    label: ":package: Use custom image"
    depends_on: base_image
    agents:
      queue: linux-arm64-small-custom # a dedicated queue using the custom base image with latest tag
    command: |
      echo "Running on custom base image"
      whoami
      node --version
      npm --version
