steps:
  - key: create_custom_base_image
    label: ":docker: Create custom base image"
    agents:
      queue: linux-arm64-small-default # a dedicated queue using the default base image
    command: |
      export REGISTRY="$(nsc workspace describe -o json -k registry_url)"
      export SERVICE="base" # name of the image
      export DOCKER_REPOSITORY="$${REGISTRY}/$${SERVICE}:latest"

      docker buildx build \
        --no-cache \
        --file .buildkite/Dockerfile.build \
        --build-arg BUILDKITE_BUILD_NUMBER="$$BUILDKITE_BUILD_NUMBER" \
        --platform linux/amd64,linux/arm64 \
        --tag "$${DOCKER_REPOSITORY}" \
        --progress plain \
        --push .

      echo "=== Custom Base Image Created ==="
      echo "Build #$$BUILDKITE_BUILD_NUMBER"
      echo "Repository: $${DOCKER_REPOSITORY}"
      buildkite-agent annotate --style "success" ":rocket: Image pushed to \`$${DOCKER_REPOSITORY}\` (Build #$$BUILDKITE_BUILD_NUMBER) :rocket:"

  - key: use_custom_base_image
    label: ":package: Use custom base image"
    depends_on: create_custom_base_image
    agents:
      queue: linux-arm64-small-custom # a dedicated queue using the custom base image with latest tag
    command: |
      echo "=== Using Custom Base Image ==="
      echo "Build #$$BUILDKITE_BUILD_NUMBER"
      echo "Image markers:"
      cat /custom-image-marker
      cat /build-number-marker
